package elrh.softman.utils.factory;

import elrh.softman.logic.db.SourcesDBManager;
import elrh.softman.logic.db.orm.PlayerInfo;
import elrh.softman.logic.enums.PlayerGender;
import org.apache.commons.lang3.StringUtils;

import java.util.Random;

public class PlayerFactory {

    // faces generated by "This Person Does Not Exist"
    // the number of available images shall increse over the time
    private static final int AVAILABLE_FACES = 21;

    public static PlayerInfo getRandomPlayerInfo(PlayerGender gender, int birth, int number) {
        PlayerInfo player =  new PlayerInfo(getRandomPlayerName(gender.toString()), gender, birth, number);
        setRandomPlayerImg(player);
        return player;
    }

    private static String getRandomPlayerName(String gender) {
        return SourcesDBManager.getInstance().getRandomFirstName(gender) + " " + SourcesDBManager.getInstance().getRandomLastName();
    }

    private static void setRandomPlayerImg(PlayerInfo player) {
        if (player.getAge() > 18) {
            int face = new Random().nextInt(0, AVAILABLE_FACES) + 1;
            player.setImg("faces/" + player.getGender().toString() + StringUtils.leftPad(String.valueOf(face), 5, "0") + ".jpg");
        } else {
            if (player.getGender() == PlayerGender.F) {
                player.setImg("vecteezy/avatar-girl.jpg");
            } else {
                player.setImg("vecteezy/avatar-boy.jpg");
            }
        }
    }

}
