package elrh.softman.utils.factory;

import elrh.softman.logic.core.Player;
import elrh.softman.logic.core.data.PlayerInfo;
import elrh.softman.logic.enums.PlayerGender;
import elrh.softman.logic.interfaces.INameSource;
import lombok.Setter;
import org.apache.commons.lang3.StringUtils;

import java.util.Random;

public class PlayerFactory {

    // faces generated by "This Person Does Not Exist" (https://thispersondoesnotexist.com/)
    // the number of available images will increase over the time
    private static final int AVAILABLE_FACES = 46;

    @Setter
    private static INameSource nameSource;

    public static Player getRandomPlayer(PlayerGender gender, int birth, int number) {
        var playerInfo =  new PlayerInfo(getRandomPlayerName(gender), gender, birth, number);
        setRandomPlayerImg(playerInfo);

        var player = new Player();
        player.setPlayerInfo(playerInfo);
        return player;
    }

    private static String getRandomPlayerName(PlayerGender gender) {
        if (nameSource == null) {
            return "Player";
        }
        return nameSource.getRandomFirstName(gender) + " " + nameSource.getRandomLastName();
    }

    private static void setRandomPlayerImg(PlayerInfo player) {
        if (player.getAge() > 18) {
            int face = new Random().nextInt(0, AVAILABLE_FACES) + 1;
            player.setImg("faces/" + player.getGender().toString() + StringUtils.leftPad(String.valueOf(face), 5, "0") + ".jpg");
        } else {
            if (player.getGender() == PlayerGender.F) {
                player.setImg("vecteezy/avatar-girl.jpg");
            } else {
                player.setImg("vecteezy/avatar-boy.jpg");
            }
        }
    }

}
